#
# Diese Datei enthält einige Einstellungen die beim Programmstart bereits 
# bekannt sein müssen und deshalb nicht über die Benutzeroberfläche abgefragt
# werden können.
#
# Um zu verhindern dass Deine Einstellungen beim nächsten Update überschrieben werden
# erzeuge bitte eine Kopie dieser Datei unter dem Namen stationadmin.conf und ändere nur
# diese Kopie.

#
# Verzeichnis für Dateien
# Normalerweise legt Station Admin seine Dateien im Homeverzeichnis des Benutzers 
# in einem Ordner namens laut.fm/ ab. Um ein anderes Verzeichnis zu verweden 
# entferne bitte das # vor der Zeile unten und gib das Verzeichnis an.
# Hinweis an Windows-User: Bitte verwendet / anstatt \
#

# data.dir = c:/stationadmin/

#
# Verzeichnis für die Konfigurationsdatei
# Normalerweise liegt die settings.xml-Datei mit den Konfigurationsdaten direkt
# im Stationsverzeichnis innerhalb des Datenverzeichnisses. Um ein anderes Verzeichnis
# zu verwenden kommentiere die Zeile unten aus und gebe den Pfad an.
# Hinweis an Windows-User: Bitte verwendet / anstatt \
#
# settings.dir = c:/stationadmin/config

#
# Proxy-Server
# Um einen Proxy-Server zu verweden entferne bitte das # am Anfang der kommenden
# Zeilen und gib Server und Port an.
#

# proxy.host = hostname
# proxy.port = 80
